# Uncomment the next line to define a global platform for your project
 platform :ios, '16'

target 'LZWechat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LZWechat
  # Swift常用扩展、组件、协议，方便项目快速搭建，提供完整清晰的Demo示例，不断的完善中...... https://github.com/JoanKing/JKSwiftExtension
  pod 'JKSwiftExtension'
  
  #  SwiftUI package to beautifully display and handle permissions https://github.com/jevonmao/PermissionsSwiftUI
  pod 'PermissionsSwiftUI'
  pod 'SwifterSwift'
  
#  Liquid
#StepperView
#PopupView
#AlertX
#ActivityIndicatorView
#MarkdownUI
#SlideOverCard
#SwiftUICharts


  target 'LZWechatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LZWechatUITests' do
    # Pods for testing
  end

end
